"use client";

import Image from "next/image";
import { motion } from "framer-motion";

const cars = [
  { src: "/generated/car-volume.png", label: "Crossover SUV", segment: "Volume" },
  { src: "/generated/car-premium.png", label: "Executive Sedan", segment: "Premium" },
  { src: "/generated/car-luxury.png", label: "Performance Coupé", segment: "Exotic" },
  { src: "/generated/car-bakkie.png", label: "Double-cab", segment: "Utility" },
  { src: "/generated/car-ev.png", label: "Electric SUV", segment: "EV" },
  { src: "/generated/dashboard.png", label: "Cabin Detail", segment: "Interior" },
  { src: "/generated/wheel-detail.png", label: "Wheel Detail", segment: "Macro" },
  { src: "/generated/key-fob.png", label: "Key Fob", segment: "Macro" },
];

// Duplicate for seamless loop
const loop = [...cars, ...cars];

export default function CarMarquee() {
  return (
    <section className="relative py-24 bg-[#020c07] overflow-hidden border-y border-white/[0.06]">
      <div className="absolute inset-0 bg-grid opacity-15" />

      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.7 }}
        className="relative mx-auto max-w-6xl px-6 mb-12"
      >
        <div className="flex items-end justify-between flex-wrap gap-4">
          <div>
            <span className="section-label">Every Vehicle. Every Buyer.</span>
            <h3 className="mt-3 heading-md max-w-xl">
              From <span className="text-emerald-400">Hilux</span> to <span className="text-emerald-400">hypercar</span>.
            </h3>
          </div>
          <p className="font-mono text-[11px] uppercase tracking-[0.2em] text-white/25 max-w-xs">
            Our agents find buyers across every segment of the SA market.
          </p>
        </div>
      </motion.div>

      {/* Marquee */}
      <div className="relative">
        {/* Edge fades */}
        <div className="absolute left-0 top-0 bottom-0 w-32 bg-gradient-to-r from-[#020c07] to-transparent z-10 pointer-events-none" />
        <div className="absolute right-0 top-0 bottom-0 w-32 bg-gradient-to-l from-[#020c07] to-transparent z-10 pointer-events-none" />

        <motion.div
          className="flex gap-6"
          animate={{ x: ["0%", "-50%"] }}
          transition={{
            duration: 60,
            repeat: Infinity,
            ease: "linear",
          }}
        >
          {loop.map((car, i) => (
            <div
              key={`${car.label}-${i}`}
              className="relative shrink-0 w-[420px] h-[260px] overflow-hidden border border-white/[0.06] bg-white/[0.02] group"
            >
              <Image
                src={car.src}
                alt={car.label}
                fill
                className="object-cover opacity-70 group-hover:opacity-100 transition-opacity duration-700 group-hover:scale-105"
                sizes="420px"
              />
              {/* Overlay */}
              <div className="absolute inset-0 bg-gradient-to-t from-[#020c07] via-[#020c07]/30 to-transparent" />

              {/* Label */}
              <div className="absolute bottom-4 left-5 right-5 flex items-end justify-between">
                <div>
                  <div className="text-[14px] text-white/85 font-light">
                    {car.label}
                  </div>
                  <div className="font-mono text-[10px] uppercase tracking-[0.25em] text-emerald-400/60 mt-1">
                    {car.segment}
                  </div>
                </div>
                <div className="h-1.5 w-1.5 rounded-full bg-emerald-500/60 animate-pulse" />
              </div>
            </div>
          ))}
        </motion.div>
      </div>

      {/* Footer note */}
      <motion.div
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        viewport={{ once: true }}
        transition={{ duration: 0.6, delay: 0.3 }}
        className="relative mx-auto max-w-6xl px-6 mt-12 text-center"
      >
        <p className="font-mono text-[10px] uppercase tracking-[0.25em] text-white/20">
          Imagery generated by Gemini Nano Banana &middot; Concept renders
        </p>
      </motion.div>
    </section>
  );
}
