"use client";

import { motion, useInView } from "framer-motion";
import { useRef } from "react";
import Image from "next/image";
import { Trophy, Music, Users } from "lucide-react";
import WindowFrame from "./WindowFrame";

const sampleChart = [
  { rank: 1, name: "Toyota Hilux", segment: "Bakkie", weeks: 142, change: "—" },
  { rank: 2, name: "VW Polo Vivo", segment: "Hatch", weeks: 89, change: "+1" },
  { rank: 3, name: "Toyota Corolla Cross", segment: "SUV", weeks: 67, change: "—" },
  { rank: 4, name: "Ford Ranger", segment: "Bakkie", weeks: 122, change: "-1" },
  { rank: 5, name: "Suzuki Swift", segment: "Hatch", weeks: 48, change: "+2" },
  { rank: 6, name: "Hyundai Grand i10", segment: "Hatch", weeks: 35, change: "+3" },
  { rank: 7, name: "Toyota Fortuner", segment: "SUV", weeks: 156, change: "-2" },
  { rank: 8, name: "Isuzu D-Max", segment: "Bakkie", weeks: 41, change: "—" },
  { rank: 9, name: "Haval Jolion", segment: "SUV", weeks: 22, change: "NEW" },
  { rank: 10, name: "Chery Tiggo 4 Pro", segment: "SUV", weeks: 18, change: "NEW" },
];

export default function CarsCharts() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, amount: 0.15 });

  return (
    <section id="charts" className="relative py-32 bg-[#030f0a] overflow-hidden">
      {/* Showroom background — generated by Nano Banana */}
      <div className="absolute inset-0 z-0">
        <Image
          src="/generated/showroom-empty.png"
          alt=""
          fill
          className="object-cover opacity-25 mix-blend-screen pointer-events-none"
        />
        <div className="absolute inset-0 bg-gradient-to-b from-[#030f0a] via-[#030f0a]/70 to-[#030f0a]" />
      </div>
      <div className="absolute inset-0 bg-dots opacity-30 z-0" />

      <div className="relative mx-auto max-w-6xl px-6">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7 }}
        >
          <div className="flex items-center gap-3 mb-2">
            <span className="section-label">Cars Charts</span>
            <span className="font-mono text-[10px] uppercase tracking-[0.25em] text-emerald-400/80 border border-emerald-500/30 bg-emerald-500/[0.06] px-2 py-0.5">
              LAUNCHING Q2 2026
            </span>
          </div>
          <h2 className="mt-4 heading-xl max-w-4xl">
            The Billboard charts
            <br />
            for <span className="text-emerald-400">South African cars</span>.
          </h2>
          <div className="mt-6 flex items-start gap-3 max-w-2xl">
            <div className="mt-1.5 h-px w-8 bg-emerald-500/40 shrink-0" />
            <p className="text-[15px] leading-relaxed text-white/50">
              We built Visio Charts for music. Now we&apos;re building it for cars.
              A weekly public chart of South Africa&apos;s most loved, most sold,
              and most desired vehicles &mdash; powered by sales data, search
              data, and a community of car enthusiasts. Free. Public. Fun.
            </p>
          </div>
        </motion.div>

        {/* Chart preview */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7, delay: 0.2 }}
          className="mt-16"
        >
          <WindowFrame title="cars.charts/sa-top10" variant="browser">
            <div className="p-8">
              {/* Header */}
              <div className="border-b border-white/[0.06] pb-5 mb-5 flex items-start justify-between flex-wrap gap-4">
                <div>
                  <div className="flex items-center gap-2">
                    <Trophy className="h-4 w-4 text-emerald-500/60" />
                    <span className="font-mono text-[10px] uppercase tracking-[0.3em] text-emerald-400/60">
                      SA Top 10 &middot; Week of April 6, 2026
                    </span>
                  </div>
                  <h3 className="mt-2 text-2xl font-extralight tracking-tight text-white">
                    The People&apos;s Cars
                  </h3>
                </div>
                <div className="flex items-center gap-2 font-mono text-[10px] text-white/30">
                  <Users className="h-3 w-3" />
                  <span>SAMPLE PREVIEW</span>
                </div>
              </div>

              {/* Chart table */}
              <div ref={ref} className="space-y-1">
                {sampleChart.map((row, i) => (
                  <motion.div
                    key={row.rank}
                    initial={{ opacity: 0, x: -8 }}
                    animate={isInView ? { opacity: 1, x: 0 } : {}}
                    transition={{ duration: 0.4, delay: i * 0.05, ease: [0.16, 1, 0.3, 1] as const }}
                    className="grid grid-cols-12 gap-0 px-4 py-3 hover:bg-white/[0.02] transition-colors border-b border-white/[0.04]"
                  >
                    <div className="col-span-1 font-mono text-xl font-extralight text-emerald-400/70">
                      {String(row.rank).padStart(2, "0")}
                    </div>
                    <div className="col-span-5 flex flex-col justify-center">
                      <span className="text-[14px] text-white/80 font-medium">
                        {row.name}
                      </span>
                      <span className="font-mono text-[10px] uppercase tracking-wider text-white/30 mt-0.5">
                        {row.segment}
                      </span>
                    </div>
                    <div className="col-span-3 flex items-center">
                      <span className="font-mono text-[11px] text-white/30">
                        {row.weeks} wks on chart
                      </span>
                    </div>
                    <div className="col-span-3 flex items-center justify-end">
                      <span
                        className={`font-mono text-[11px] ${
                          row.change === "NEW"
                            ? "text-emerald-400/80"
                            : row.change.startsWith("+")
                            ? "text-emerald-400/60"
                            : row.change.startsWith("-")
                            ? "text-red-400/40"
                            : "text-white/20"
                        }`}
                      >
                        {row.change}
                      </span>
                    </div>
                  </motion.div>
                ))}
              </div>

              {/* Footer */}
              <div className="mt-6 pt-5 border-t border-white/[0.06] flex items-start justify-between flex-wrap gap-4">
                <p className="font-mono text-[10px] text-white/25 max-w-md leading-relaxed">
                  Sample data for preview only. Real charts launch Q2 2026 with
                  weekly NAAMSA-verified sales data, search trends, and fan voting.
                </p>
                <Music className="h-4 w-4 text-emerald-500/30" />
              </div>
            </div>
          </WindowFrame>
        </motion.div>

        {/* Three feature cards */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="mt-16 grid gap-px md:grid-cols-3 bg-white/[0.04] border border-white/[0.06]"
        >
          <div className="bg-[#030f0a] p-8">
            <span className="font-mono text-[10px] uppercase tracking-[0.25em] text-emerald-500/50">
              The Charts
            </span>
            <h4 className="mt-3 text-lg font-extralight text-white">Weekly Top 10s</h4>
            <p className="mt-3 text-[12px] leading-relaxed text-white/35">
              Bakkies, Hatchbacks, SUVs, Luxury, Performance, Electric. Six categories,
              updated every Monday. NAAMSA-verified.
            </p>
          </div>
          <div className="bg-[#030f0a] p-8">
            <span className="font-mono text-[10px] uppercase tracking-[0.25em] text-emerald-500/50">
              The Community
            </span>
            <h4 className="mt-3 text-lg font-extralight text-white">Fans Vote</h4>
            <p className="mt-3 text-[12px] leading-relaxed text-white/35">
              Free public account. Vote on your favourites. Share photos. Submit your
              ride. The car community South Africa deserves.
            </p>
          </div>
          <div className="bg-[#030f0a] p-8">
            <span className="font-mono text-[10px] uppercase tracking-[0.25em] text-emerald-500/50">
              The Show
            </span>
            <h4 className="mt-3 text-lg font-extralight text-white">Coming soon</h4>
            <p className="mt-3 text-[12px] leading-relaxed text-white/35">
              We&apos;re partnering with SA&apos;s top automotive influencers for a
              weekly show that breaks down the charts. Reveal who&apos;s rising,
              who&apos;s falling, and why.
            </p>
          </div>
        </motion.div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="mt-12 text-center"
        >
          <a
            href="/charts"
            className="inline-flex items-center gap-2 font-mono text-[11px] uppercase tracking-[0.2em] text-emerald-400/60 hover:text-emerald-400 transition-colors border-b border-emerald-500/20 pb-1"
          >
            Get notified when Cars Charts launches →
          </a>
        </motion.div>
      </div>
    </section>
  );
}
